// ESLint flat config（改进方案 C1–C3；devDependencies 实际版本见 package.json，当前 ^10）。
// 作用域：src/scripts = node ESM；test = node ESM（node:test 是 import 不是全局）；
// ui = classic script 的浏览器环境（无 import/export，sourceType 必须是 script）。
// tools/ 与 data/ 是本地未跟踪目录，不进 lint。
import globals from 'globals';

// 全部规则 error（no-unused-vars 也已在 2026-09-30 的清零批次里清到 0 ——
// 含删除 ui/app.js 的 5 个上游遗产零调用函数及其配套死代码；此后 no-unused-vars
// 是硬门禁，新增未用变量会直接红）。
// caughtErrors:'none'：catch (e) 不用 e 无罪，空 catch 由 no-empty(error) 盯住。
const baseRules = {
  'no-undef': 'error',
  'no-unused-vars': ['error', { args: 'after-used', ignoreRestSiblings: true, caughtErrors: 'none' }],
  // no-empty 自 C2 起为 error：空块必须写明“有意忽略”的原因
  'no-empty': ['error', { allowEmptyCatch: false }],
  'no-dupe-keys': 'error',
  'no-unreachable': 'error',
  'no-constant-condition': 'error',
  'no-prototype-builtins': 'error',
};

const nodeScope = {
  languageOptions: { ecmaVersion: 2024, sourceType: 'module', globals: { ...globals.node } },
  rules: baseRules,
};

// classic script 时代跨文件共享的全局（定义散在 ui/app.js、ui/core/*、ui/pages/*，被别的
// ui 文件与外挂脚本引用）—— 清单的判定是**分层无关**的，别假设"定义只在 app.js + core"。
// 显式声明“这些是有意共享的全局”，而不是豁免规则 —— 改进方案 §1.3 的符号清单。
// 这份清单同时也是**冻结契约**：test/ui-contract.test.mjs 断言任一文件引用的"别的文件顶层名字"
// 都在这里，且这里的每个名字都还有定义、确实被别的文件用到（防腐烂/防冗余）。
// B 档 ESM 化完成后这批声明应随之删除（改为显式 import）。
// 注：CONSOLE_MARKER 曾列在这里，但它只在 core/api.js 内部使用（没有别的文件引用），
// 2026-09-30 随 §11 C2 的契约用例清掉；renderProbeResult 同理，2026-10-01 它随 widgets.js
// 的按域拆分进了 pages/usage.js（唯一调用方），不再是跨文件全局。
const uiSharedGlobals = {
  $: 'readonly',
  $$: 'readonly',
  addChannelFeed: 'readonly',
  afterRender: 'readonly',
  api: 'readonly',
  appendChatMessageRows: 'readonly',
  applyPersonaDraft: 'readonly',
  applyTheme: 'readonly',
  appReady: 'readonly',
  askForConfirmation: 'readonly',
  ASR_SERVICES: 'readonly',
  asrHostOf: 'readonly',
  asrServiceOf: 'readonly',
  asrServiceOptions: 'readonly',
  ASSET_KINDS: 'readonly',
  bindCrossSectionControls: 'readonly',
  bindSettingsEvents: 'readonly',
  bindTtsControls: 'readonly',
  bootLogs: 'readonly',
  captureTimeControlRule: 'readonly',
  CHAT_MSG_MORE: 'readonly',
  CHAT_MSG_PAGE: 'readonly',
  chatMsgSortCache: 'readonly',
  chatNameOf: 'readonly',
  chatsRefreshTimer: 'readonly',
  clampInt: 'readonly',
  closeModelModal: 'readonly',
  CONVERSATION_MODE_LABEL: 'readonly',
  CORE_SERVICE_LINKS: 'readonly',
  currentPersonaId: 'readonly',
  currentThinkingRaw: 'readonly',
  defaultPersonaFold: 'readonly',
  deletePriceDialog: 'readonly',
  effectivePriceFor: 'readonly',
  esc: 'readonly',
  experimentalFeatureLaunchPatch: 'readonly',
  extraBodyText: 'readonly',
  fmtClock: 'readonly',
  fmtRate: 'readonly',
  fmtRemainingMs: 'readonly',
  fmtTime: 'readonly',
  fmtTok: 'readonly',
  fmtTokens: 'readonly',
  fmtWaitRemain: 'readonly',
  fmtYuan: 'readonly',
  formatChatTitle: 'readonly',
  formatElapsed: 'readonly',
  formatReleaseNotes: 'readonly',
  formatRevision: 'readonly',
  FRIEND_OPPORTUNITY_STATUS: 'readonly',
  FRIEND_PROPOSAL_REASON: 'readonly',
  FRIEND_PROPOSAL_STATUS: 'readonly',
  getThemePref: 'readonly',
  groupSliderPosForUi: 'readonly',
  hasOwnPrice: 'readonly',
  hideLoading: 'readonly',
  hostOfUrl: 'readonly',
  identityPilotSettingsPatch: 'readonly',
  ignoreUpdateVersion: 'readonly',
  impressionMetaLabel: 'readonly',
  INCIDENT_SEVERITY_LABELS: 'readonly',
  INCIDENT_STATE_LABELS: 'readonly',
  INCOMING_FRIEND_STATUS: 'readonly',
  initChatScrollLoader: 'readonly',
  initialServiceNote: 'readonly',
  initSessionScrollLoader: 'readonly',
  isSplitThinking: 'readonly',
  lastDetailFp: 'readonly',
  launchExperimentalFeature: 'readonly',
  legacyServiceDeployed: 'readonly',
  lifecycleAggregate: 'readonly',
  lifecycleRemainingText: 'readonly',
  lifecycleRunsFor: 'readonly',
  lifecycleStateOf: 'readonly',
  listPoller: 'readonly',
  loadAssetObservatory: 'readonly',
  loadChats: 'readonly',
  loadDailyMomentsStatus: 'readonly',
  loadExperimentalFeatureStatuses: 'readonly',
  loadFriendFeaturePage: 'readonly',
  loadFriendOpportunities: 'readonly',
  loadFriendProposals: 'readonly',
  loadGroupGameView: 'readonly',
  loadIdentityFeaturePage: 'readonly',
  loadIncidentFeaturePage: 'readonly',
  loadIncomingFriendRequests: 'readonly',
  LOADING_REVEAL_MS: 'readonly',
  loadingLogs: 'readonly',
  loadingRevealed: 'readonly',
  loadingRevealTimer: 'readonly',
  loadingStatus: 'readonly',
  loadMemoryView: 'readonly',
  loadQzoneInteractionStatus: 'readonly',
  loadRemindersView: 'readonly',
  loadSessionDetail: 'readonly',
  loadSessions: 'readonly',
  loadSettings: 'readonly',
  loadSlangFeaturePage: 'readonly',
  loadTimeControlStatus: 'readonly',
  loadUsageView: 'readonly',
  matchPriceTable: 'readonly',
  memThreshold: 'readonly',
  MODEL_SERVICES_UI: 'readonly',
  modelModalShell: 'readonly',
  MOMENT_STATUS_LABELS: 'readonly',
  momentStatusLabel: 'readonly',
  mulOf: 'readonly',
  normalizeAsrMax: 'readonly',
  normalizeStickerMax: 'readonly',
  onChannelFeedAction: 'readonly',
  onebotIssueText: 'readonly',
  onebotStatusLineHtml: 'readonly',
  openBatchPriceModal: 'readonly',
  openBlocklistModal: 'readonly',
  openMemoryModelPicker: 'readonly',
  openModelAddModal: 'readonly',
  openModelDeleteModal: 'readonly',
  openModelPicker: 'readonly',
  openPersonaCreateModal: 'readonly',
  openPriceDialog: 'readonly',
  openWhitelistPicker: 'readonly',
  paramActiveForProbability: 'readonly',
  parseList: 'readonly',
  parsePersonaCard: 'readonly',
  patchKeyedList: 'readonly',
  pauseAutoUpdate: 'readonly',
  pendingSessionDetail: 'readonly',
  PERSONA_BAD_SECTIONS: 'readonly',
  PERSONA_RULE_EXAMPLES: 'readonly',
  PERSONA_SECTION_EMOJI: 'readonly',
  PERSONA_TAG_SECTIONS: 'readonly',
  personaBaseCardId: 'readonly',
  personaCollapsedSections: 'readonly',
  personaDescCache: 'readonly',
  personaEditingSection: 'readonly',
  personaEditNote: 'readonly',
  personaParseCache: 'readonly',
  personaSectionBody: 'readonly',
  personaViewTimer: 'readonly',
  pickedGroups: 'readonly',
  pollUntilReady: 'readonly',
  priceDialogState: 'readonly',
  priceTxt: 'readonly',
  QARegistry: 'readonly',
  QZONE_ACTION_LABELS: 'readonly',
  QZONE_RUN_LABELS: 'readonly',
  readAssetImage: 'readonly',
  refreshAutoUpdateStatus: 'readonly',
  refreshIntervalMs: 'readonly',
  refreshModelPriceCard: 'readonly',
  refreshStatus: 'readonly',
  refreshStatusImpl: 'readonly',
  renderAsrSection: 'readonly',
  renderBanner: 'readonly',
  renderChannelFeeds: 'readonly',
  renderChatSection: 'readonly',
  renderControlHub: 'readonly',
  renderDailyMomentsSection: 'readonly',
  renderExperimentalSettingsSection: 'readonly',
  renderExperimentalSettingsSectionImpl: 'readonly',
  renderFriendFeaturePageImpl: 'readonly',
  renderGroupChecklist: 'readonly',
  renderGroupGameSection: 'readonly',
  renderIdentityFeaturePageImpl: 'readonly',
  renderIncidentFeaturePageImpl: 'readonly',
  renderLifecycleOverview: 'readonly',
  renderLifecycleOverviewImpl: 'readonly',
  renderMemoryList: 'readonly',
  renderMomentWindowRow: 'readonly',
  renderPersonaSection: 'readonly',
  renderPriceFeedStatus: 'readonly',
  renderQzoneInteractionSection: 'readonly',
  renderRemindersSection: 'readonly',
  renderSessionDetail: 'readonly',
  renderSessionList: 'readonly',
  renderSettings: 'readonly',
  renderSettingsImpl: 'readonly',
  renderThinkingSeg: 'readonly',
  renderTimeRuleEditor: 'readonly',
  renderUpdateCheckNote: 'readonly',
  requestExperimentOwnerUin: 'readonly',
  resolveTheme: 'readonly',
  resumePause: 'readonly',
  revealLoadingIfSlow: 'readonly',
  runChannelProbe: 'readonly',
  runManualUpdate: 'readonly',
  runUpdateFromNotice: 'readonly',
  saveConfig: 'readonly',
  saveMemberNote: 'readonly',
  savePriceDialog: 'readonly',
  scheduleChatsRefresh: 'readonly',
  scheduleSessionRender: 'readonly',
  segOfProbability: 'readonly',
  serviceTileState: 'readonly',
  serviceUrl: 'readonly',
  SESSION_KEEP: 'readonly',
  SESSION_PAGE: 'readonly',
  sessionRenderScheduled: 'readonly',
  setBoxError: 'readonly',
  setHtmlIfChanged: 'readonly',
  setLoadingStatus: 'readonly',
  setStatusLabel: 'readonly',
  SLANG_RESEARCH_STATUS: 'readonly',
  sliderDesc: 'readonly',
  sliderToTierUI: 'readonly',
  sliderToTierUI_tierToSlider: 'readonly',
  splitRowsHtml: 'readonly',
  startConsolidateTicker: 'readonly',
  startLifecycleTicker: 'readonly',
  startListPoller: 'readonly',
  startUpdateProgressTicker: 'readonly',
  startWaitTicker: 'readonly',
  state: 'readonly',
  STATUS_LABEL: 'readonly',
  statusRefreshTimer: 'readonly',
  STICKER_LEVELS: 'readonly',
  STICKER_MAX_CHOICES: 'readonly',
  stickerMaxSelectOptions: 'readonly',
  switchTab: 'readonly',
  syncClampedInputs: 'readonly',
  syncGraduatedFeatureNavigation: 'readonly',
  syncPersonaButtons: 'readonly',
  syncPriceDialogBilling: 'readonly',
  syncThinkingUi: 'readonly',
  THEME_ICON: 'readonly',
  THEME_LABEL: 'readonly',
  THEME_VALUES: 'readonly',
  THINKING_PURPOSES: 'readonly',
  thinkingStops: 'readonly',
  THREAD_STATE_LABEL: 'readonly',
  TIME_DAYS: 'readonly',
  TIME_RULE_LABELS: 'readonly',
  timeControlTargetOptions: 'readonly',
  TOOL_CAT_ORDER: 'readonly',
  TOOL_META: 'readonly',
  TRIGGER_KIND_LABEL: 'readonly',
  triggerKindLabel: 'readonly',
  uiServiceOfUrl: 'readonly',
  UPDATE_ACTIVE_STATUSES: 'readonly',
  UPDATE_PHASE_LABELS: 'readonly',
  UPDATE_STATUS_LABELS: 'readonly',
  updateChatMessagesBody: 'readonly',
  updateOnebotStatusLine: 'readonly',
  updateProgressElapsed: 'readonly',
  updateTimeControlLiveState: 'readonly',
  USAGE_RANGES: 'readonly',
  usageLastData: 'readonly',
  usageLoadToken: 'readonly',
  usageRange: 'readonly',
};

export default [
  { ignores: ['node_modules/**', 'data/**', 'tools/**', '_staging/**'] },
  { files: ['src/**/*.js'], ...nodeScope },
  { files: ['scripts/**/*.mjs'], ...nodeScope },
  { files: ['test/**/*.mjs'], ...nodeScope },
  {
    files: ['ui/**/*.js'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'script',
      globals: { ...globals.browser, ...uiSharedGlobals },
    },
    rules: baseRules,
  },
  {
    // 共享内核 / 页面域 / 文案表：**定义就是给后续 script 用的**（classic script 的全局词法
    // 环境，跨文件共享），单文件视角必然报"未用"——只在这一组关掉 no-unused-vars。
    // （注意别把 app.js 与外挂插件并进来：它们是业务/插件代码，no-unused-vars 要留着。）
    files: ['ui/core/**/*.js', 'ui/pages/**/*.js', 'ui/i18n/**/*.js'],
    rules: {
      'no-unused-vars': 'off',
    },
  },
  {
    // 体积闸门（改进方案 §11）：**ui/ 下每个文件**都不得超过 1800 行。
    // 2026-10-01 现状：app.js 1019（它已从 13,130 行的单体缩成骨架，按它自己的规矩纳入约束）、
    // 最长的是 ui/pages/settings-bind.js 1756（设置页绑定：调度器 + 四段切出来的绑定块）。
    // 阈值沿革：方案原写 1500，第一次拆分时提到 1800 —— 因为按依赖层级抽出的叶子桶
    // （core/widgets.js）出来就是 1606 行；那一桶现已按调用方拆开，但设置页绑定的四段本身
    // 合计 1536 行 > 1500，再往下切只能是任意切分，所以保留 1800（仍在 13k 量级之下）。
    files: ['ui/**/*.js'],
    rules: {
      'max-lines': ['warn', { max: 1800 }],
    },
  },
];
